### ISSUE TITLE
Link with javascript:; href

### ISSUE THREAD

**Issue by pedrofs** [lawlesscreation/jquery.clickable#1]
Hi,

I have a link that will trigger some javascript behavior. Is there a way to just fire the click in the corresponding `<a>` element when the clickable gets clicked?

Best,
Pedro.

**Comment by lawlesscreation** [comment]
@pedrofs I don't think it can do what you're asking, but if you build an example test case I can have a look to see if it's an option that could be added.

**Comment by pedrofs** [comment]
Here is a simple example: https://jsfiddle.net/drsbq0zj/

**Comment by pedrofs** [comment]
Here a simple example: https://jsfiddle.net/drsbq0zj/1/

Thanks for the quick reply :)

**Comment by lawlesscreation** [comment]
To be honest, I'm a bit of a fan of progressive enhancement so having JavaScript in the HTML like that would be something I try to avoid :)

That said, it did lead me to wonder if you could do this with a callback? Turns out there's one already in there! - though it's not in the documentation which I will update. Would the callback allow you to run whatever JavaScript event you want to trigger on click?

**Comment by lawlesscreation** [comment]
Ah... the `callbackAfter()` fires after the element has been made clickable. Maybe adding a `callbackAfterClick()` to fire after it has been clicked might do it.

**Comment by pedrofs** [comment]
Actually I'm not using javascript inside the HTML there. The `href="javascript:;"` is just to warn that this specific link will trigger a javascript behavior.

The problem of adding a callback to the `jqueryClickable` is that all my clickable links will then trigger the callback.

Did you get what I mean?

**Comment by pedrofs** [comment]
I'll close the issue. It's does not make sense to use the the plugin for this specific situation.

Thanks for you attention.
